name: example
description: A sample command-line application.

environment:
  sdk: ^3.10.1

dependencies:
  enum_annotation: ^0.0.4

dev_dependencies:
  build_runner: ^2.9.0
  test: ^1.26.3
  build: '>=4.0.3'
  enum_generator:
    path: ../